apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drone-agent
  labels:
    app: drone-agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"    
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"    
    spec:
      containers:
        - image: drone/agent:{{ .Values.drone.version }}
          imagePullPolicy: IfNotPresent
          name: drone
          env:
            - name: DRONE_SERVER
              value: drone-server:{{ .Values.service.http.grpcPort }}
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: drone-secret              
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock