apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
type: Opaque
data:
  {{ if .Values.drone.secret }}
  drone-secret: {{ .Values.drone.secret | b64enc }}
  {{ else }}
  drone-secret: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
  github-client: {{ .Values.github.client | b64enc }}
  github-secret: {{ .Values.github.secret | b64enc }}
